[package]
name = "slides2-md-to-str"
version = "0.1.0"
authors = ["Igor Laborie <ilaborie@gmail.com>"]
edition = "2018"

[dependencies]
jni = "0.11"
pulldown-cmark = "0.3"

[lib]
crate_type = ["cdylib"]
