[package]
name = "slides2-compile-scss"
version = "0.1.0"
authors = ["Igor Laborie <ilaborie@gmail.com>"]
edition = "2018"

[dependencies]
jni = "0.10.2"
sass-rs = "0.2.1"

[lib]
crate_type = ["cdylib"]
